  
           let movies = [{
                key: 1,
                name: 'Monsters, Inc.',
                stars:[5, 5, 4],
                comment: [`I've seen this 2001 Pixar film loads of times and it's absolutely brilliant. It's probably one of the best Pixar films of all time. It's one of my favourite Disney and Pixar films of all time as well. Pixar sure did a great job and they're total geniuses. The voice acting is excellent especially from John Goodman himself.`,[`This is a wonderful movie with so many emotions. It’s my second favorite Pixar movie. The characters are all so great. The favorites are Sully, Mike, and even Boo. I like how in the monster world you had to get scream energy from scaring little children in the human world. I thought it was interesting. I also like the door chase   Which is one of my favorite scenes. They go door to door. I had a lot of fun with this movie when I was a kid. And I still watch even today. I highly recommend watching it. 👍👍👍`],[`In this Pixar film, two monsters named Mike and Sully must protect a young human girl from an evil plot. In typical Pixar fashion they really up their game in the animation department with each film. In this movie you can see their improvement in the textures, specifically Sully’s hair and their snow animation. The story here is great and the relationship between Sully and Boo, the young human girl, is the heart of the film. Randell, the antagonist, is voiced well by Steve Buscemi and is a threatening presence throughout the film. The very last scene of the movie always leaves me with the warm-fuzzies. Highly recommend you check this movie out!
                Was this review helpful to you?`]],
                synopsis: `James Sullivan and Mike Wazowski are monsters, they earn their living scaring children and are the best in the business... even though they're more afraid of the children than they are of them. When a child accidentally enters their world, James and Mike suddenly find that kids are not to be afraid of and they uncover a conspiracy that could threaten all children across the world.`,
                releaseDate: 2001,
                coverPhoto: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sgheSKxZkttIe8ONsf2sWXPgip3.jpg'
            },
            {
                key: 2,
                name: `Finding Nemo`,
                stars: [4,5,5],
                comment: [`A young clownfish named Nemo is taken by humans and his father, Marlin, transferces the ocean to find him, with a little help from a regal blue tang named Dory. This is a great film! The first two scenes do a great job to endear you to both Marlin and Nemo. Dory is instantly likable and relatable. As Marlin goes on his journey and develops his character, the characters he meets are all memorable and iconic. The aquarium crew are all memorable as well. The animation is top notch and really captures the underwater environment in a believable way. Ellen DeGeneres stands out in the voice acting department, by creating a unique and memorable character in Dory. One of the best films Pixar has done, highly recommended!
                `,[`I love this movie, it’s certainly one of my favorite movies of Pixar. It describes everything from the ocean yet the characters are very likable and memorable. The more I see it, the better it gets in my opinion. Although I felt sad that Nigel never knew that Marlin found Nemo after helping Marlin and Dory, I really wished he knew since he really helped the story. Overall, this movie is awesome, the music score from Thomas Newman, the story, heck even the visual effects on the early pixar is still impressive for 2003. Its likeable and I would definitely recommend this for the entire family. 10/10
                `],[`FINDING NEMO is a beautiful, delightful animated adventure about a small clownfish in search of his son, who's been caught and put into a human fish tank.  This movie has great heart, values, and cinematography. It has entertaining and comedic characters. Marlin, little clownfish Nemo's father goes to great lengths and through perilous adventures to find and rescue his son. Nemo has a stunted fin; but with the support of his family and friends learns to overcome his disability.
                `]],               
                synopsis: `Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.`,
                releaseDate: 2003,
                coverPhoto: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg'     
            },
            {
                key: 3,
                name: `Ratatouille`,
                stars: [5,4,3],
                comment: [[`MASTERPIECE. I loved everything aside from uhhh, well, I guess some characters. Anyway, great message, great writing. I'd also like to point out all these details such as earlier when Remy was scouting the various crevices of places in Paris he saw a couple arguing.- the woman tried to shoot the guy but missed and almost hit Remy and he noticed they made up after it with a kiss and forced Linguini to kiss Colette to stop the argument so that was cool and also that dog's shadow resembled Dug from Up so nice one. Anyway, unsurprisingly the animation is shellshockingly amazing. Plus this movie is hella funny, Chef Skinner was the best part. Overall, my favourite Pixar movie by far at this point.
                (10/10 would eat again)
                `], [`Story: 5/5. It's what Pixar does best, isn't it? Even though I hate rats, this film built a story I could get behind and champion. Remy is a likable character, and the supporting cast is all very effective and (surprisingly) realistic. The story, despite its fantasy, involved a good chunk of real moments and reasonable reactions - just when I thought something was pushing it, it pulled back appropriately. The double-villain idea was executed well.

                Visuals: 3/5. It is over a decade old now, I know, but the animation really isn't aging too well at times. There are many interesting camera movements and Paris is beautiful. There is just often a stark lack of detail and the rats followed a very basic template.
                
                Sound: 3/5. Michael Giacchino has such a distinct musical style that I knew it was him behind the music before I had proof. His style was very effective in adding excitement and regional flavour to the film. It was very obviously set in Paris and sounded the way you would assume Paris sounds.
                
                11/15: It took me many years to see this but it holds up well and I am glad to have finally seen it.`],[`This has been a pretty fun and  partially hilarious experience. The meals that the rat cooks look delicious as heck due to the way everything is beautifully animated. The movements for the characters are also fluid. I was not a big fan of our main character and  I myself don't feel like his redemption arc even  saved him from all of his flaws. I did enjoy the critic and really wished that there was more of him.
                `]],
                synopsis: `Remy, a resident of Paris, appreciates good food and has quite a sophisticated palate. He would love to become a chef so he can create and enjoy culinary masterpieces to his heart's delight. The only problem is, Remy is a rat. When he winds up in the sewer beneath one of Paris' finest restaurants, the rodent gourmet finds himself ideally placed to realize his dream.`,
                releaseDate: 2007,
                coverPhoto: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg' 
            },
            {
                key: 4,
                name: `WALLE-E`,
                stars: [5,5,5],
                comment: [[`“WALL-E” is a masterpiece! I am nearly eighteen years old (as of 21st July 2022) and it is one of my favourite films. It is also Pixar Animation Studios’ best movie in my opinion. It’s very well-paced, entertaining and heartfelt, the animation is incredible, the story is interesting and unique, the characters are likeable and well-developed, the themes (waste disposal, human impact on the environment, consumerism, technology, obesity, nostalgia, love, loneliness…) are interesting and handled well, the voice acting, sound design, visuals and editing are solid, the music is brilliant, the minimal use of dialogue in the first half is clever, it feels timeless, and it has a good balance of sci-fi, romance, drama and comedy.

                I was glad when I found out that this film had recently been selected for preservation by the Library of Congress.
                `],[`This has to be the darkest yet most innovative Pixar movie ever made. Humans abandoning Earth and living in space could be the future thanks to climate change and pollution, but I might be fine with that so we can escape this nightmare. Wall E being the only inhabitant is kinda cute with how treats the world, and I love how he interacts with Eve. It's amusing how he causes trouble for her, and I also love how the humans live their new lives. They're controlled by machines for everything; they also had to turn on the machine in charge of them so they could get back home. The ending was kinda boring for the computer's defeat, and I also don't like how REX-yes, the one from Toy Story-is in this movie as an Easter egg, mainly because it's make it look like Andy and the toy gang are all dead, and Rex doesn't even move, making it a little more creepy. I do love the ending. First Wall E must save Eve, then she must do the same for him. I also love how they celebrate the ending with Earth being habitable again. I'm hoping that Pixar does make a sequel to this film, but if they do it will either be a long time, or it will be boring/bad. I love this film to death and I highly recommend it if you haven't seen it.
                `],[`This movie really brings out the character to the robots, and you can tell what kind of person they are, even though their speech is very limited. I 100% recommend this movie for anyone looking for a cute animation to watch during quarantine, or one just to get really attached to. The ending is amazing and sweet, and if you don't even get to the verge of crying you have no soul. 20/10, my favourite movie. It's also on Disney plus, but I do own the Dvd itself. Oh, and a good mention to the cockroach that keeps Wall-E company before Eve! He was cute
                `]],
                synopsis: `WALL·E is the last robot left on an Earth that has been overrun with garbage and all humans have fled to outer space. For 700 years he has continued to try and clean up the mess, but has developed some rather interesting human-like qualities. When a ship arrives with a sleek new type of robot, WALL·E thinks he's finally found a friend and stows away on the ship when it leaves.`,
                releaseDate: 2008,
                coverPhoto: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg' 
            },
            {
                key: 5,
                name: `Up`,
                stars: [5,5,3],
                comment: [[`Honestly, “Up” has been my go to movie since 5th grade when I first saw it on the television. 
                I was very small to understand the first 10 minutes. Don’t get me wrong I knew it was sad but didn’t had the sense to embrace it up until now. The last time I saw this movie was 3-4 years ago. And after that, just imagining the first 10 minutes use to tear my eye up. As an adult tbh, it takes a lot of courage to watch this particular movie. It’s kid friendly with an emotional connection and ofc the definition of love. The “move mountains for you kinda love” is described here. It’s about two adventurous kids who fell in love and later spend their entire together. They had there ups and downs but always wished to visit The Paradise Falls in Latin America, but fate had other plans. Mr. Fredrickson, a widowed gentleman moved his beloved home with his wife’s memories to the paradise fall via flying the entire home there! Ofc in his adventure he met a young scout and a dog named dug, and a mysterious creature. From the beginning till the end it’s an emotional roller coaster of love, embrace and care, no matter if you are a human or a rare species of bird. The thing I love the most about this movie is, it describes the philosophy of letting go once they leave your life permanently. Mr. fredrickson missed his beloved late wife and embraced her at any cost until he realised his late wife left him a memoir where she mentioned,” thank you for the adventures, now go have one of your own.” That is where he realised that he can always keep and embrace her as long as his is alive, and finally let go of the home he was holding on to for his late wife. He loved, he got hurt and eventually he healed.`],[`The film has so much care being put in it's story with interesting characters and villains, and comedic scenes. Up does a spectacular job at making the watcher feel sad for Carl, showing his childhood first you'll think he'll be happy, but he ends up becoming a grumpy old man. His backstory is emotional and happy at the same time. It's one of the only parts in a movie that I've cried at. Seeing Carl opening up to buddy, Kevin and Dug is just amazing. A twist villain in this really surprised me, you can feel that he truly is a broken man. Searching for Kevin for like 100 years and Carl just walks in with him. I could say this about any movie but this one just flies above animated movies like a god.
`],[`Honestly, I’m not an over the top fan of this movie, it peaks in the first like 10 minutes, and that’s about it, afterward your left with a decent Pixar movie, just because the first 10 minutes was good doesn’t make it the best. You have to take the movie as a whole and not just bits and pieces of it. Personally I don’t feel like it deserved its win over Coraline AKA (ONE OF MY FAVORITE MOVIES OF ALL TIME) but it’s still a somewhat decent Pixar movie to check out.
`]],
                synopsis: `Carl Fredricksen spent his entire life dreaming of exploring the globe and experiencing life to its fullest. But at age 78, life seems to have passed him by, until a twist of fate (and a persistent 8-year old Wilderness Explorer named Russell) gives him a new lease on life.`,
                releaseDate: 2009,
                coverPhoto: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vpbaStTMt8qqXaEgnOR2EE4DNJk.jpg' 
            },
            {
                key: 6,
                name: `The Incredibles`,
                stars: [5,4,4],
                comment: [[`Pixar's first ever PG-Rated film, "The Incredibles" is such a heart-pumping and breathtaking experience that it's unbelievable to think about all the hard work that went into it. All the incredible (no pun intended) details on the characters, as well as all the action and explosion shots, makes this one of their most thrilling roller coaster rides of all time. Even after 15 years since it first sprung into action on the big screen, I'd still want to jump onto that same roller coaster. With very strong and charming characters, animation that ups the bar way over the mark from what I can expect, an action-packed story with some very funny moments, and classy music from the great Michael Giacchino, this movie is everything you can ask for when it comes to serious, yet very artistic and action-filled blockbusters. Undeniably an animation masterpiece!
                `],[`I wasn't expecting The Incredibles to be as good as it was, it was inventive, funny and original, all the things that I look for in an animated film. I don't think it is Pixar's best, that's Toy Story, but it's certainly not the weakest, that's Cars though that was a worthy film as well. The animation is spot on, and just adds to the inventive feel of the film, and is helped enormously by an innovative plot that is the source of the film's originality. The story is very fast-paced, if perhaps a little slow to begin with, and the script is filled with humour to satisfy even the fussiest child. The characters are very well-done, thanks to the excellent voice cast, standouts are Craig T. Nelson and Holly Hunter, and My Name is Earl's Jason Lee is a big surprise as the villain Syndrome. Brad Bird's Edna was a hoot too. The film however, does have two flaws, it is overlong and sometimes drags consequently, and it is a little too violent at times, the last half-hour especially. Overall, an excellent family film, not perfect, but anybody who's seen some of the Disney direct to video sequels, save one or two exceptions will agree that the Incredibles does a much better job at entertaining than they did. 8/10 Bethany Cox.
                `],[`It is a great and humorous movie.
                It is the best movie according to me after Tangled.
                Only problem in the movie is the action.
                Too much action for me .
                I mean i don't like fighting much.
                Anyways the movie is awesome and worth watching.`]],
                synopsis: `Bob Parr has given up his superhero days to log in time as an insurance adjuster and raise his three children with his formerly heroic wife in suburbia. But when he receives a mysterious assignment, it's time to get back into costume.`,
                releaseDate: 2004,
                coverPhoto: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1cFyFox588zZEczborLAQHIVS1p.jpg' 
            }]


        const starImage = 'https://wpclipart.com/computer/icons_2/.cache/star.png/'
export default movies